batches_per_epoch: 10
cond_dim: 1
decoder_layers:
- 100
- 100
device: cuda
encoder_layers:
- 100
- 100
epochs: 300
gamma: 0.75
latent_dim: 2
lr: 0.001
output_dim: 2
prior_layers:
- 100
- 100
save_epochs: 100
step_size: 50
val_epochs: 10
